import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export type RevenuePdfInput = {
  organizerName: string;
  asOfLabel: string;
  summary: {
    grossRevenue: number;
    platformFee: number;
    eligiblePayout: number;
    realPayments: number;
    couponPayments: number;
    freeCoupons: number;
    freeCouponFaceValue: number;
    totalPaidOut: number;
    availableBalance: number;
  };
  trips: Array<{
    tripTitle: string;
    totalBookings: number;
    grossAmount: number;
    eligibleAmount: number;
  }>;
  transactions: Array<{
    paidAt: string;
    memberName: string;
    tripTitle: string;
    grossAmount: number;
    amountPaid: number;
    type: string;
  }>;
};

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function money(n: number): string {
  return `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function buildRevenueSummaryHtml(data: RevenuePdfInput): string {
  const s = data.summary;
  const rows = data.transactions
    .map(
      (t) =>
        `<tr><td>${esc(t.paidAt)}</td><td>${esc(t.memberName)}</td><td>${esc(t.tripTitle)}</td><td>${money(t.grossAmount)}</td><td>${money(t.amountPaid)}</td><td>${esc(t.type)}</td></tr>`,
    )
    .join("");

  const tripRows = data.trips
    .map(
      (t) =>
        `<tr><td>${esc(t.tripTitle)}</td><td>${t.totalBookings}</td><td>${money(t.grossAmount)}</td><td>${money(t.eligibleAmount)}</td></tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body{font-family:system-ui,-apple-system,sans-serif;background:#fff;color:#111;padding:24px;font-size:12px;}
h1{font-size:20px;margin:0 0 8px;}
h2{font-size:14px;margin:24px 0 8px;color:#333;}
.muted{color:#666;font-size:11px;}
table{width:100%;border-collapse:collapse;margin-top:8px;}
th,td{border:1px solid #ddd;padding:6px 8px;text-align:left;}
th{background:#f5f5f5;font-size:11px;}
.footer{margin-top:32px;font-size:10px;color:#999;}
</style></head><body>
<div style="font-weight:800;font-size:18px;">Trip-Sync</div>
<h1>Revenue summary</h1>
<p class="muted">Organizer: ${esc(data.organizerName)} · As of ${esc(data.asOfLabel)}</p>

<h2>Summary</h2>
<table>
<tr><th>Metric</th><th>Amount</th></tr>
<tr><td>Gross revenue (cash)</td><td>${money(s.grossRevenue)}</td></tr>
<tr><td>Platform fee (10%)</td><td>${money(s.platformFee)}</td></tr>
<tr><td>Real payments</td><td>${money(s.realPayments)}</td></tr>
<tr><td>Coupon payments</td><td>${money(s.couponPayments)}</td></tr>
<tr><td>Free coupons (bookings)</td><td>${s.freeCoupons} (${money(s.freeCouponFaceValue)} face value)</td></tr>
</table>

<h2>Trip breakdown</h2>
<table>
<tr><th>Trip</th><th>Bookings</th><th>Gross</th><th>Eligible</th></tr>
${tripRows}
</table>

<h2>Transactions</h2>
<table>
<tr><th>Date</th><th>Member</th><th>Trip</th><th>Gross</th><th>Paid</th><th>Type</th></tr>
${rows}
</table>

<p class="footer">Generated by Trip-Sync · Confidential</p>
</body></html>`;
}

/* ------------------------------------------------------------------ */
/*  Payout history (used by PayoutScreen)                              */
/* ------------------------------------------------------------------ */

export type PayoutHistoryRow = {
  amount: number;
  status: string;
  date: string;
  utr?: string | null;
};

export type PayoutHistoryInput = {
  organizerName: string;
  rows: PayoutHistoryRow[];
};

/**
 * Build a styled HTML document containing a payout-history summary
 * (totals grouped by status) followed by a detailed table.
 */
export function buildPayoutHistoryHtml(input: PayoutHistoryInput): string {
  const { organizerName, rows } = input;

  /* ---- Summary totals by status ---- */
  const totals: Record<string, number> = {};
  for (const r of rows) {
    const st = r.status?.toLowerCase() || "unknown";
    totals[st] = (totals[st] || 0) + (r.amount || 0);
  }
  const summaryRows = Object.entries(totals)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([st, amt]) =>
        `<tr><td>${esc(st.charAt(0).toUpperCase() + st.slice(1))}</td><td>${money(amt)}</td></tr>`,
    )
    .join("");

  /* ---- Detail table rows ---- */
  const detailRows = rows
    .map((r) => {
      const amt = money(r.amount || 0);
      const st = esc(r.status || "");
      const dt = r.date ? esc(String(r.date).slice(0, 10)) : "—";
      const u = r.utr ? esc(r.utr) : "—";
      return `<tr><td>${amt}</td><td>${st}</td><td>${dt}</td><td>${u}</td></tr>`;
    })
    .join("");

  const totalAmount = money(rows.reduce((sum, r) => sum + (r.amount || 0), 0));

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body{font-family:system-ui,-apple-system,sans-serif;background:#fff;color:#111;padding:24px;font-size:12px;}
h1{font-size:20px;margin:0 0 4px;}
h2{font-size:14px;margin:20px 0 8px;color:#333;}
.sub{color:#666;font-size:11px;margin-bottom:16px;}
table{width:100%;border-collapse:collapse;margin-top:6px;}
th,td{border:1px solid #ddd;padding:7px 8px;text-align:left;}
th{background:#f5f5f5;font-size:11px;}
.total-row td{border-top:2px solid #999;font-weight:700;}
.footer{margin-top:28px;font-size:10px;color:#999;}
</style></head><body>
<div style="font-weight:800;font-size:18px;">Trip-Sync</div>
<h1>Payout History</h1>
<p class="sub">${esc(organizerName)} · Generated ${new Date().toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" })} · ${rows.length} payout${rows.length === 1 ? "" : "s"}</p>

<h2>Summary by status</h2>
<table>
<tr><th>Status</th><th>Total</th></tr>
${summaryRows}
<tr class="total-row"><td>Grand Total</td><td>${totalAmount}</td></tr>
</table>

<h2>Details</h2>
<table>
<tr><th>Amount</th><th>Status</th><th>Date</th><th>UTR</th></tr>
${detailRows}
</table>

<p class="footer">Generated by Trip-Sync · Confidential</p>
</body></html>`;
}

/* ------------------------------------------------------------------ */
/*  Share / print PDF                                                  */
/* ------------------------------------------------------------------ */

/**
 * Generate a PDF from the given HTML, then try to share it.
 * Falls back to Print.printAsync when sharing is unavailable.
 */
export async function shareRevenuePdf(html: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });

  try {
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        dialogTitle: "Trip-Sync — Export PDF",
        UTI: "com.adobe.pdf",
      });
      return;
    }
  } catch {
    // sharing threw — fall through to printAsync
  }

  // Fallback: use the system print dialog
  await Print.printAsync({ uri });
}
